### ISSUE TITLE
More "Flavors"? 

### ISSUE THREAD

**Issue by Nooby-001** [AnubisNekhet/AnuPpuccin#20]
LOVE this theme and I'm glad the dev is back!
Could we have more theme colors? I use "Frappe" on the dark theme and it's just too dark and meh, I know we can use custom backgrounds now but I'd rather just click a button and get a nice, not too dark not too light note background.

Thank you!

**Comment by AnubisNekhet** [comment]
There's [this snippet](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/extended-colorschemes.css) which adds more colors to the theme. I deliberately chose not to add these flavors since they increase the theme size by a lot, but I've added them as a snippet for people who want more colors :)

**Comment by njohnson43** [comment]
Also loving the theme! Dumb question here as I'm not CSS savvy - how do I make use of the snippet? I've tried adding it to /.obsidian/snippets but Style Settings doesn't seem to be recognizing it.

EDIT: I figured it out. I hadn't realized that I needed to do a few more steps in the Standard Obsidian "Appearance" settings. Thanks!

**Comment by Nooby-001** [comment]
Thank you again!
