### ISSUE TITLE
Option to make Tabs clickable on the topmost pixel of the Window.

### ISSUE THREAD

**Issue by albertoloscerritos** [AnubisNekhet/AnuPpuccin#216]
The following post from the obsidian forum explains how to feature would work and goes into more detail:

https://forum.obsidian.md/t/make-tabs-clickable-on-the-topmost-pixel-of-the-window/44930?u=cerros

> Currently in Obsidian, you have to position your cursor at the correct height to hit a tab, which takes some precision.
Every browser or other tab-based app that I’ve used is set up so that moving your mouse to the top edge of the screen still allows you to click on the tab in that position. This way it’s possible to just move the cursor as far up as it goes and click, making switching or rearranging tabs a lot easier.

Thanks.

**Comment by AnubisNekhet** [comment]
Closing this issue since it is not achievable through CSS afaik. Having it implemented in the core theme or having a separate element in the electron application would be a much preferable alternative. If anyone has any solutions, please share it in [Discussions](https://github.com/AnubisNekhet/AnuPpuccin/discussions)!

**Comment by albertoloscerritos** [comment]
Ok I see. Thanks anyway.
Have a great day 👍
