### ISSUE TITLE
[Feature Request] Add custom background again

### ISSUE THREAD

**Issue by shard77** [AnubisNekhet/AnuPpuccin#237]
**Feature Description**
Hello, why has the custom background feature been deleted in the latest release? I am using it since a long time and really like the feel/look of it..

**Comment by ProudBenzene** [comment]
Or if the removement is because of the Obsidian official policies, could you please save the background picture feature as a css snippet, just like the rainbow folder snippet?

If so, I am convinced that many people would appreciate it! After all, the background picture feature works so well!

I hope you'll reconsider, thank you!

**Comment by sosacode20** [comment]
I am another one who will appreciate the comeback of custom background

**Comment by AuroraDizon** [comment]
It's basically the only reason I used this theme.

**Comment by AuroraDizon** [comment]
The CSS Snippet is in the main code: https://github.com/AnubisNekhet/AnuPpuccin/commit/7894fbd7aab7ca008719299596343e69ccff200a

According to the commits it was removed because of Obsidian policy: https://github.com/AnubisNekhet/AnuPpuccin/commits/main

**Comment by mh166** [comment]
From what I see, #235 provides some context why it was removed.
