### ISSUE TITLE
The custom background feature has been moved to [this snippet](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/custom-background.css) to comply with obsidian theme guidelines.

### ISSUE THREAD

**Issue by lucasbcgeo** [AnubisNekhet/AnuPpuccin#255]
The custom background feature has been moved to [this snippet](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/snippets/custom-background.css) to comply with obsidian theme guidelines.

_Originally posted by @AnubisNekhet in https://github.com/AnubisNekhet/AnuPpuccin/issues/247#issuecomment-1881751616_

Could you please show how it works? Is it possible to use a jpeg file? Do you know any png internet repository  ?

**Comment by syrth-io** [comment]
first, follow [this guide](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) and for step three, instead of creating a CSS file, **save the snippet to the folder that opens**. you can click the highlighted button (at the top right of the code box) to save the CSS file directly:
![screenshot of the "download raw file" box highlighted with the tooltip label shown above it](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/36fcaf3c-e572-4020-8810-c5896fff01f2)

after enabling, open Style Settings (if you don't have it, you'll need to download it from the Obsidian Community Plugins store). you'll need to toggle on the custom background option, and then in the custom background box, enter the URL in the following format, substituting the word "REPLACE" for the URL of your image:

`url("REPLACE")`

you can either use the same image or different ones for light and dark mode!

any common image format should work, so yes, jpegs too. you can find hotlink-able (i.e., link directly to the image without downloading and re-uploading to your own image host) free images at places like [Unsplash](https://unsplash.com/), [Pexels](https://www.pexels.com/), and [Pixabay](https://pixabay.com/), among others. you can also upload an image you already have to somewhere like [Imgur](https://imgur.com/) (be sure to use the image's **direct** link).

I hope this helps! if you need any further explanation or anything was unclear, please let me know.
