### ISSUE TITLE
[feature request] Alternate checkboxes

### ISSUE THREAD

**Issue by rodrigo-rufino** [AnubisNekhet/AnuPpuccin#6]
It would be very nice to have alternate checkboxes similar to other themes (like [Minimal](https://github.com/kepano/obsidian-minimal#alternate-checkboxes) and Primary).

**Comment by AnubisNekhet** [comment]
Alternate checkboxes definitely seem like a great idea, but I have them a bit low on my priority list since this theme is more about having a framework which doesn't take away from vanilla by forcing features unless you willingly allow it. This is why I haven't added speech bubbles into the theme as well. This isn't to say I won't be doing it though 😆 I'll figure out a good set of checkboxes.

**Comment by AnubisNekhet** [comment]
Done :)

**Comment by rodrigo-rufino** [comment]
Thank you very much!!!
