### ISSUE TITLE
浅色主题修改theme accent似乎不起作用，只有Solarized能正常修改

### ISSUE THREAD

**Issue by VKWF** [AnubisNekhet/AnuPpuccin#9]
<img width="1136" alt="截屏2022-10-29 03 41 46" src="https://user-images.githubusercontent.com/38653497/198720625-a6b06f83-0498-4c9e-b3c2-45317f5579de.png">

**Comment by AnubisNekhet** [comment]
Hi! The accent is fixed for certain themes such as Nord and Rosebox, which means that you cannot change them. I added fixed theme accents because the accent guide requests me to use a specific color for the theme accent.
![image](https://user-images.githubusercontent.com/102488279/198725682-c9899fc2-2cc2-4799-8856-6ac3c1051289.png)
Please check the table in the README.md file to see which themes have a fixed theme accent. Any theme that has `Accent value is hardcoded into the theme.` has a fixed theme accent.
