### ISSUE TITLE
[Bug] Regular quotes formatting

### ISSUE THREAD

**Issue by vi-cat** [AnubisNekhet/AnuPpuccin#98]
**Describe the bug**
All of the callboxes work beautifully, however, the regular blockquote does not seem to be formatting in the same style.

**To Reproduce**
1. Create a new blockquote in a file `> hello world`
2. Create a callout in the same file `> [!info] hello`
3. Notice the formatting discrepancy

**Expected behavior**
I would expect the blockquotes to follow the same style as the rest of the callouts. In this case, the borders, paddings, border radiuses needs to be adjusted to match the rest of the callout settings.

**Screenshots**
<img width="731" alt="Theme_test_-_Cortex_-_Obsidian_v1_1_15" src="https://user-images.githubusercontent.com/2243885/221352140-d4e6b46b-b272-4df7-bd46-50fb5376da48.png">

**Additional context**
Brand new install of AnuPpuccin.

**Comment by AnubisNekhet** [comment]
Blockquotes have not been tampered with since they follow the default obsidian styling. The callout (what i presume is `vanilla`) tries to replicate the pre 1.0 callout style which is the reason why I've chosen that specific border width.
I don't have any particular plans to change blockquotes right now since they seem fine to me as-is.
